# vim:ft=hyprlang
general {
  lock_cmd = pidof hyprlock || hyprlock
  before_sleep_cmd = loginctl lock-session
  after_sleep_cmd = niri msg output eDP-1 on
  unlock_cmd = pw-play ~/.config/scripts/assets/oxp.wav
}

listener {
    timeout = 300
    on-timeout = light -O && light -S 10
    on-resume = light -I
}

listener {
  timeout = 600
  on-timeout = loginctl lock-session
}

listener {
  timeout = 900
  on-timeout = niri msg output eDP-1 off
  on-resume = niri msg output eDP-1 on
}

listener {
  timeout = 1500
  on-timeout = systemctl hibernate
}
